export const seedProperties = [
  {
    id: 'prop-grand-oak',
    slug: 'the-grand-oak-sanctuary-villa',
    title: 'The Grand Oak Sanctuary Villa',
    type: 'Villa',
    intent: 'buy',
    price: '₹4.85 Cr',
    priceValue: 48500000,
    pricePerSqFt: '₹9,326 / sq.ft',
    location: 'Whitefield, Bengaluru',
    city: 'Bengaluru',
    neighbourhood: 'Palm Meadows Zone',
    bedrooms: 4,
    bathrooms: 5,
    area: '5,200 sq.ft',
    description:
      'A masterfully crafted private villa nestled in the lush, quiet enclave of Whitefield. Designed with double-height vaulted ceilings, private heated lap pool, landscaped zen gardens, and European imported hardwood fixtures.',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=85',
    ],
    amenities: [
      'Private Swimming Pool',
      'Solar Powered Grid (10kW)',
      'Home Theater Room',
      'Automated Climate Control',
      'Landscaped Courtyard',
      '24/7 Gated Security',
      'Servant Quarters',
      'EV Charging Station',
    ],
    highlights: [
      '100% Clear Title Deed verified by Senior Advocates',
      'Built in 2024 with earthquake-resistant RCC frame',
      'BBMP ' + 'A-Khata' + ' & RERA Approved',
    ],
    furnishing: 'Semi-Furnished',
    parkingSpaces: 3,
    yearBuilt: 2024,
    verified: true,
    featured: true,
    recent: true,
    status: 'available',
    agent: {
      name: 'Vikram Patel',
      phone: '+91 98450 18234',
      email: 'vikram.patel@securestay.com',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=300&q=80',
      agencyName: 'SecureStay Advisory Prime',
      licenseNumber: 'RERA-KA-2023-88910',
    },
  },
  {
    id: 'prop-oakwood-villa',
    slug: 'oakwood-villa-sarjapur',
    title: 'Oakwood Villa — Sarjapur',
    type: 'Villa',
    intent: 'buy',
    price: '₹3.40 Cr',
    priceValue: 34000000,
    pricePerSqFt: '₹8,500 / sq.ft',
    location: 'Sarjapur Road, Bengaluru',
    city: 'Bengaluru',
    neighbourhood: 'Carmelaram Green Belt',
    bedrooms: 4,
    bathrooms: 4,
    area: '4,000 sq.ft',
    description:
      'Gated community luxury villa surrounded by dense greenery. Features an open-concept kitchen, private rooftop terrace lounge, expansive family suites, and seamless road connectivity to Outer Ring Road.',
    images: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?auto=format&fit=crop&w=1200&q=85',
    ],
    amenities: [
      'Clubhouse & Gym',
      'Tennis & Badminton Courts',
      'Rainwater Harvesting',
      'High-Speed Fiber Network',
      'Italian Marble Flooring',
      '24/7 Security Patrol',
    ],
    highlights: ['Zero common wall construction', 'Proximity to top international schools', 'RERA registered community'],
    furnishing: 'Furnished',
    parkingSpaces: 2,
    yearBuilt: 2023,
    verified: true,
    featured: true,
    recent: true,
    status: 'available',
    agent: {
      name: 'Pooja Hegde',
      phone: '+91 98450 77123',
      email: 'pooja.h@securestay.com',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
      agencyName: 'SecureStay Advisory Prime',
      licenseNumber: 'RERA-KA-2022-77192',
    },
  },
  {
    id: 'prop-urban-heights',
    slug: 'urban-heights-electronic-city',
    title: 'Urban Heights — Electronic City',
    type: 'Apartment',
    intent: 'buy',
    price: '₹1.15 Cr',
    priceValue: 11500000,
    pricePerSqFt: '₹6,388 / sq.ft',
    location: 'Electronic City Phase 1, Bengaluru',
    city: 'Bengaluru',
    neighbourhood: 'Infosys & Tech Corridor',
    bedrooms: 3,
    bathrooms: 3,
    area: '1,800 sq.ft',
    description:
      'Contemporary high-rise corner residence boasting undisturbed panoramic skyline views, private balconies, designer modular kitchen, and instant access to the elevated expressway and metro line.',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=85',
    ],
    amenities: ['Infinity Sky Pool', 'Modern Fitness Center', 'Co-working Lounge', 'Children Play Zone', 'Power Backup'],
    highlights: ['Ready to move with OC and CC', 'Walking distance to Yellow Line Metro', 'High rental demand (6.4% yield)'],
    furnishing: 'Semi-Furnished',
    parkingSpaces: 2,
    yearBuilt: 2024,
    verified: true,
    featured: true,
    recent: true,
    status: 'available',
    agent: {
      name: 'Vikram Patel',
      phone: '+91 98450 18234',
      email: 'vikram.patel@securestay.com',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=300&q=80',
      agencyName: 'SecureStay Advisory Prime',
      licenseNumber: 'RERA-KA-2023-88910',
    },
  },
  {
    id: 'prop-skyline-crest',
    slug: 'premium-city-apartment-hyderabad',
    title: 'Premium City Apartment — Hyderabad',
    type: 'Penthouse',
    intent: 'buy',
    price: '₹3.95 Cr',
    priceValue: 39500000,
    pricePerSqFt: '₹10,533 / sq.ft',
    location: 'HITEC City & Jubilee Hills, Hyderabad',
    city: 'Hyderabad',
    neighbourhood: 'Knowledge City Ridge',
    bedrooms: 4,
    bathrooms: 5,
    area: '3,750 sq.ft',
    description:
      'Ultra-exclusive duplex penthouse featuring private sky lounge, 270-degree skyline views of Durgam Cheruvu cable bridge, private elevator foyer, and bespoke Italian interior architecture.',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=85',
    ],
    amenities: ['Private Sky Elevator', 'Temperature Controlled Pool', 'Valet Parking', 'Concierge Desk', 'Helipad Access'],
    highlights: ['Private rooftop deck', 'GHMC Occupancy Certificate received', 'Zero litigation title clearance'],
    furnishing: 'Furnished',
    parkingSpaces: 3,
    yearBuilt: 2024,
    verified: true,
    featured: true,
    recent: false,
    status: 'available',
    agent: {
      name: 'Aditya Reddy',
      phone: '+91 98490 33410',
      email: 'aditya.r@securestay.com',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
      agencyName: 'SecureStay Hyderabad Luxury',
      licenseNumber: 'RERA-TS-2023-11029',
    },
  },
  {
    id: 'prop-bandra-seafront',
    slug: 'bandra-seafront-residence-mumbai',
    title: 'Bandra Seafront Luxury Apartment — Mumbai',
    type: 'Apartment',
    intent: 'buy',
    price: '₹8.75 Cr',
    priceValue: 87500000,
    pricePerSqFt: '₹35,000 / sq.ft',
    location: 'Bandra West, Mumbai',
    city: 'Mumbai',
    neighbourhood: 'Carter Road Promenade',
    bedrooms: 3,
    bathrooms: 4,
    area: '2,500 sq.ft',
    description:
      'Unrivaled Arabian Sea vistas in Mumbai’s most iconic residential neighborhood. Expansive wrap-around glass balcony, imported Greek marble, automated acoustic soundproofing, and multi-tier security.',
    images: [
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=85',
    ],
    amenities: ['Sea-facing Sundeck', 'Private Elevator', 'Automated Parking Stack', '24/7 Security Concierge'],
    highlights: ['Unobstructed Arabian Sea frontage', 'Full OC & Clear Title', 'Exclusive single unit per floor'],
    furnishing: 'Furnished',
    parkingSpaces: 2,
    yearBuilt: 2023,
    verified: true,
    featured: true,
    recent: true,
    status: 'available',
    agent: {
      name: 'Zubin Mehta',
      phone: '+91 98200 45678',
      email: 'zubin.m@securestay.com',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
      agencyName: 'SecureStay Mumbai Prime',
      licenseNumber: 'RERA-MAHA-2022-99012',
    },
  },
  {
    id: 'prop-palm-grove-goa',
    slug: 'assagao-heritage-villa-goa',
    title: 'Assagao Heritage Private Estate — Goa',
    type: 'Estate',
    intent: 'buy',
    price: '₹5.50 Cr',
    priceValue: 55000000,
    pricePerSqFt: '₹12,222 / sq.ft',
    location: 'Assagao, North Goa',
    city: 'Goa',
    neighbourhood: 'Badem Valley',
    bedrooms: 4,
    bathrooms: 5,
    area: '4,500 sq.ft',
    description:
      'Restored Indo-Portuguese heritage sanctuary situated in the fashionable village of Assagao. Private courtyard pool, antique laterite stone walls, high timber ceilings, and dense tropical landscaping.',
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85',
    ],
    amenities: ['Private Plunge Pool', 'Verandah Lounge', 'Organic Kitchen Garden', 'High-speed Fiber', 'Power Generator'],
    highlights: ['Freehold Sanad-converted land', 'High holiday rental yield (7.8% p.a.)', 'Zero noise pollution zone'],
    furnishing: 'Furnished',
    parkingSpaces: 3,
    yearBuilt: 2024,
    verified: true,
    featured: true,
    recent: true,
    status: 'available',
    agent: {
      name: 'Maria D’Souza',
      phone: '+91 98221 66543',
      email: 'maria.d@securestay.com',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
      agencyName: 'SecureStay Coastal Estates',
      licenseNumber: 'RERA-GOA-2023-45120',
    },
  },
  {
    id: 'prop-koregaon-pune',
    slug: 'koregaon-park-residence-pune',
    title: 'Koregaon Park Gated Residence — Pune',
    type: 'Apartment',
    intent: 'buy',
    price: '₹2.75 Cr',
    priceValue: 27500000,
    pricePerSqFt: '₹11,000 / sq.ft',
    location: 'Koregaon Park, Pune',
    city: 'Pune',
    neighbourhood: 'Lane 5 Green Canopy',
    bedrooms: 3,
    bathrooms: 3,
    area: '2,500 sq.ft',
    description:
      'Serene tree-lined residential apartment in Pune’s elite lifestyle quarter. Features expansive wooden deck balconies, German modular kitchen fittings, and walking proximity to premier cafes and wellness centers.',
    images: [
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=85',
    ],
    amenities: ['Clubhouse', 'Heated Pool', 'Smart Home Automation', 'Dedicated EV Charger', '24/7 Security'],
    highlights: ['Prime central location', 'PMC Sanctioned building with completion certificate', 'Low density building'],
    furnishing: 'Semi-Furnished',
    parkingSpaces: 2,
    yearBuilt: 2023,
    verified: true,
    featured: false,
    recent: true,
    status: 'available',
    agent: {
      name: 'Vikram Patel',
      phone: '+91 98450 18234',
      email: 'vikram.patel@securestay.com',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=300&q=80',
      agencyName: 'SecureStay Advisory Prime',
      licenseNumber: 'RERA-KA-2023-88910',
    },
  },
  {
    id: 'prop-golf-course-delhi',
    slug: 'golf-course-ext-penthouse-delhi-ncr',
    title: 'Golf Course Extension Penthouse — Delhi NCR',
    type: 'Penthouse',
    intent: 'buy',
    price: '₹6.25 Cr',
    priceValue: 62500000,
    pricePerSqFt: '₹13,888 / sq.ft',
    location: 'Golf Course Extension, Gurugram (Delhi NCR)',
    city: 'Delhi NCR',
    neighbourhood: 'Sector 58 Green Corridors',
    bedrooms: 4,
    bathrooms: 5,
    area: '4,500 sq.ft',
    description:
      'Opulent multi-level penthouse overlooking the Aravalli Hills and lush championship golf course greens. Double-height grand salon, private heated plunge pool, smart VRV air purification systems.',
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=85',
    ],
    amenities: ['Golf Course Facing', 'Private Jacuzzi Deck', 'Wine Cellar', 'Biometric Elevator Access', 'Triple Covered Parking'],
    highlights: ['Direct view of Aravalli green belt', 'Haryana RERA approved project', 'Immediate possession available'],
    furnishing: 'Semi-Furnished',
    parkingSpaces: 3,
    yearBuilt: 2024,
    verified: true,
    featured: true,
    recent: true,
    status: 'available',
    agent: {
      name: 'Rahul Khanna',
      phone: '+91 98100 89234',
      email: 'rahul.k@securestay.com',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80',
      agencyName: 'SecureStay NCR Advisory',
      licenseNumber: 'RERA-HR-2023-55901',
    },
  },
  {
    id: 'prop-koramangala-rental',
    slug: 'koramangala-modern-duplex-rental',
    title: 'Koramangala Executive Duplex — Bengaluru',
    type: 'Apartment',
    intent: 'rent',
    price: '₹1.25 L / mo',
    priceValue: 125000,
    pricePerSqFt: '₹52 / sq.ft',
    location: 'Koramangala 4th Block, Bengaluru',
    city: 'Bengaluru',
    neighbourhood: 'Wipro Park Vicinity',
    bedrooms: 3,
    bathrooms: 3,
    area: '2,400 sq.ft',
    description:
      'Fully furnished designer duplex home for lease in the heart of Koramangala. Includes imported Italian leather living sets, high-end kitchen appliances, and private shaded rooftop garden.',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=85',
    ],
    amenities: ['Fully Furnished', 'Private Terrace Garden', 'Power Backup', 'Dedicated Car Park', 'High-Speed WiFi'],
    highlights: ['Walking distance to 100+ fine dining cafes', 'Direct owner representation', 'Verified lease agreement format'],
    furnishing: 'Furnished',
    parkingSpaces: 2,
    yearBuilt: 2023,
    verified: true,
    featured: false,
    recent: true,
    status: 'available',
    agent: {
      name: 'Vikram Patel',
      phone: '+91 98450 18234',
      email: 'vikram.patel@securestay.com',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=300&q=80',
      agencyName: 'SecureStay Advisory Prime',
      licenseNumber: 'RERA-KA-2023-88910',
    },
  },
];

export const seedLocations = [
  {
    name: 'Bengaluru',
    city: 'Bengaluru',
    category: 'Silicon Valley of India',
    listingCount: '134+ Verified',
    typicalPrice: '₹85 L – ₹8.5 Cr',
    avgPriceSqFt: '₹7,500 / sq.ft',
    image: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80',
    description: 'Tech hubs, green suburbs, and high capital growth corridors.',
  },
  {
    name: 'Hyderabad',
    city: 'Hyderabad',
    category: 'Financial District & HITEC',
    listingCount: '86+ Verified',
    typicalPrice: '₹95 L – ₹12.0 Cr',
    avgPriceSqFt: '₹9,800 / sq.ft',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    description: 'Premier infrastructure, wide arterial roads, and booming commercial hubs.',
  },
  {
    name: 'Mumbai',
    city: 'Mumbai',
    category: 'Coastal & Commercial Capital',
    listingCount: '62+ Verified',
    typicalPrice: '₹2.5 Cr – ₹45.0 Cr',
    avgPriceSqFt: '₹32,000 / sq.ft',
    image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=800&q=80',
    description: 'Seafront residences, heritage neighborhoods, and elite financial epicenter.',
  },
  {
    name: 'Goa',
    city: 'Goa',
    category: 'Coastal Luxury & Holiday Estates',
    listingCount: '45+ Verified',
    typicalPrice: '₹1.8 Cr – ₹14.0 Cr',
    avgPriceSqFt: '₹13,500 / sq.ft',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    description: 'Private villas, heritage Indo-Portuguese estates, and high rental yield getaways.',
  },
  {
    name: 'Pune',
    city: 'Pune',
    category: 'Cultural & IT Metropolis',
    listingCount: '54+ Verified',
    typicalPrice: '₹75 L – ₹5.5 Cr',
    avgPriceSqFt: '₹8,200 / sq.ft',
    image: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?auto=format&fit=crop&w=800&q=80',
    description: 'Green foliage, elite residential quarters in Koregaon Park and Baner.',
  },
  {
    name: 'Delhi NCR',
    city: 'Delhi NCR',
    category: 'National Capital Region',
    listingCount: '78+ Verified',
    typicalPrice: '₹1.2 Cr – ₹18.0 Cr',
    avgPriceSqFt: '₹11,500 / sq.ft',
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80',
    description: 'Expansive penthouses along Golf Course Road and modern expressways.',
  },
];
